/*
 * OSCombo.cs - Functions for generating OS-architecture combos.
 * Created on: 11:39 02-12-2021
 * Author    : itsmevjnk
 */

using System;
using System.Runtime.InteropServices;

namespace HRngBackend
{
    public static class OSCombo
    {
        /*
         * public static string Combo
         *   The OS-architecture combo. Generated by the static
         *   constructor below.
         */
        public static string Combo;

        /*
         * static OSCombo()
         *   Constructor that retrieves the OS-architecture combo for
         *   the machine this library is running on.
         *   An OS-architecture combo has this form:
         *     <OS>.<Architecture>
         *   OS can be either FreeBSD, Linux, OSX or Windows.
         *   Architecture can be either X86, X64, Arm or Arm64.
         *   Input : none.
         *   Output: none.
         */
        static OSCombo()
        {
            /* Get OS */
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) Combo = "Linux";
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX)) Combo = "OSX";
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) Combo = "Windows";
            else throw new InvalidOperationException("Unsupported operating system");

            /* Get architecture */
            Combo += "." + Convert.ToString(RuntimeInformation.OSArchitecture);
        }
    }
}
