//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsFrontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsFrontend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open cookies.txt.
        /// </summary>
        internal static string DlgOpenCookiesTxt {
            get {
                return ResourceManager.GetString("DlgOpenCookiesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open EntryCollection sheet.
        /// </summary>
        internal static string DlgOpenEC {
            get {
                return ResourceManager.GetString("DlgOpenEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save EntryCollection sheet.
        /// </summary>
        internal static string DlgSaveEC {
            get {
                return ResourceManager.GetString("DlgSaveEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions have been cancelled..
        /// </summary>
        internal static string MsgActionsCancelled_Body {
            get {
                return ResourceManager.GetString("MsgActionsCancelled_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRng WinForms Frontend.
        /// </summary>
        internal static string MsgActionsCancelled_Title {
            get {
                return ResourceManager.GetString("MsgActionsCancelled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntryCollection export is successful..
        /// </summary>
        internal static string MsgActionsECExportSuccess_Body {
            get {
                return ResourceManager.GetString("MsgActionsECExportSuccess_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntryCollection export.
        /// </summary>
        internal static string MsgActionsECExportSuccess_Title {
            get {
                return ResourceManager.GetString("MsgActionsECExportSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntryCollection import is successful..
        /// </summary>
        internal static string MsgActionsECImportSuccess_Body {
            get {
                return ResourceManager.GetString("MsgActionsECImportSuccess_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntryCollection import.
        /// </summary>
        internal static string MsgActionsECImportSuccess_Title {
            get {
                return ResourceManager.GetString("MsgActionsECImportSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions have completed successfully. Do you want to save EntryCollection now?.
        /// </summary>
        internal static string MsgActionsSuccess_Body {
            get {
                return ResourceManager.GetString("MsgActionsSuccess_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRng WinForms Frontend.
        /// </summary>
        internal static string MsgActionsSuccess_Title {
            get {
                return ResourceManager.GetString("MsgActionsSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the browser/driver to the latest version ({0}, {1})?.
        /// </summary>
        internal static string MsgInitUpdate_Body {
            get {
                return ResourceManager.GetString("MsgInitUpdate_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser/driver update.
        /// </summary>
        internal static string MsgInitUpdate_Title {
            get {
                return ResourceManager.GetString("MsgInitUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser/driver updating failed (error code {0})..
        /// </summary>
        internal static string MsgInitUpdateFail_Body {
            get {
                return ResourceManager.GetString("MsgInitUpdateFail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser/driver update.
        /// </summary>
        internal static string MsgInitUpdateFail_Title {
            get {
                return ResourceManager.GetString("MsgInitUpdateFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account logged in failed ({0})..
        /// </summary>
        internal static string MsgLoginFail_Body {
            get {
                return ResourceManager.GetString("MsgLoginFail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook login.
        /// </summary>
        internal static string MsgLoginFail_Title {
            get {
                return ResourceManager.GetString("MsgLoginFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account logged in successfully..
        /// </summary>
        internal static string MsgLoginSuccess_Body {
            get {
                return ResourceManager.GetString("MsgLoginSuccess_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook login.
        /// </summary>
        internal static string MsgLoginSuccess_Title {
            get {
                return ResourceManager.GetString("MsgLoginSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect verification code entered, please try again..
        /// </summary>
        internal static string MsgLoginWrongOTP_Body {
            get {
                return ResourceManager.GetString("MsgLoginWrongOTP_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook two-factor authentication.
        /// </summary>
        internal static string MsgLoginWrongOTP_Title {
            get {
                return ResourceManager.GetString("MsgLoginWrongOTP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding columns to EntryCollection..
        /// </summary>
        internal static string StaActionsAddECColumns {
            get {
                return ResourceManager.GetString("StaActionsAddECColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting comments..
        /// </summary>
        internal static string StaActionsGetComments {
            get {
                return ResourceManager.GetString("StaActionsGetComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting comments and mentions..
        /// </summary>
        internal static string StaActionsGetCommentsMentions {
            get {
                return ResourceManager.GetString("StaActionsGetCommentsMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting reactions lookup table..
        /// </summary>
        internal static string StaActionsGetLut {
            get {
                return ResourceManager.GetString("StaActionsGetLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting reactions..
        /// </summary>
        internal static string StaActionsGetReactions {
            get {
                return ResourceManager.GetString("StaActionsGetReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting shares..
        /// </summary>
        internal static string StaActionsGetShares {
            get {
                return ResourceManager.GetString("StaActionsGetShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Facebook post..
        /// </summary>
        internal static string StaActionsLoadPost {
            get {
                return ResourceManager.GetString("StaActionsLoadPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start to begin....
        /// </summary>
        internal static string StaActionsReady {
            get {
                return ResourceManager.GetString("StaActionsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarizing checking data..
        /// </summary>
        internal static string StaActionsSummarize {
            get {
                return ResourceManager.GetString("StaActionsSummarize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading 7-Zip..
        /// </summary>
        internal static string StaInit7zDownload {
            get {
                return ResourceManager.GetString("StaInit7zDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-Zip executable found..
        /// </summary>
        internal static string StaInit7zFound {
            get {
                return ResourceManager.GetString("StaInit7zFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching latest browser and driver version..
        /// </summary>
        internal static string StaInitBrowserFetchVer {
            get {
                return ResourceManager.GetString("StaInitBrowserFetchVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found local browser installation..
        /// </summary>
        internal static string StaInitBrowserFound {
            get {
                return ResourceManager.GetString("StaInitBrowserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find local browser installation, will download now..
        /// </summary>
        internal static string StaInitBrowserNotFound {
            get {
                return ResourceManager.GetString("StaInitBrowserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting browser..
        /// </summary>
        internal static string StaInitBrowserStart {
            get {
                return ResourceManager.GetString("StaInitBrowserStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating/Downloading browser and driver..
        /// </summary>
        internal static string StaInitBrowserUpdate {
            get {
                return ResourceManager.GetString("StaInitBrowserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser and driver have been updated to the latest version..
        /// </summary>
        internal static string StaInitBrowserUpdated {
            get {
                return ResourceManager.GetString("StaInitBrowserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found local browser driver..
        /// </summary>
        internal static string StaInitDriverFound {
            get {
                return ResourceManager.GetString("StaInitDriverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find local browser driver, will download now..
        /// </summary>
        internal static string StaInitDriverNotFound {
            get {
                return ResourceManager.GetString("StaInitDriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*).
        /// </summary>
        internal static string StrAllFiles {
            get {
                return ResourceManager.GetString("StrAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV spreadsheets (*.csv).
        /// </summary>
        internal static string StrCSVSpreadsheet {
            get {
                return ResourceManager.GetString("StrCSVSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel workbooks (*.xlsx,*.xls).
        /// </summary>
        internal static string StrExcelWorkbook {
            get {
                return ResourceManager.GetString("StrExcelWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned {1}.
        /// </summary>
        internal static string StrFuncReturnVal {
            get {
                return ResourceManager.GetString("StrFuncReturnVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in (UID: {0}).
        /// </summary>
        internal static string StrLoggedInUID {
            get {
                return ResourceManager.GetString("StrLoggedInUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string StrNotLoggedIn {
            get {
                return ResourceManager.GetString("StrNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP entry refused by user.
        /// </summary>
        internal static string StrOTPRefused {
            get {
                return ResourceManager.GetString("StrOTPRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt).
        /// </summary>
        internal static string StrTextFiles {
            get {
                return ResourceManager.GetString("StrTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string StrUnknown {
            get {
                return ResourceManager.GetString("StrUnknown", resourceCulture);
            }
        }
    }
}
